# src.features — feature engineering & selection
"""Feature engineering: technical indicators, rolling stats, selection, EDA, and stationarity."""

from src.features.autocorrelation_diagnostics import (
    AutocorrelationReport,
    LjungBoxRawResult,
    RunLengthResult,
    VarianceRatioResult,
    autocorrelation_report,
    compute_acf_pacf,
    ljung_box_raw,
    multi_asset_autocorrelation_summary,
    multi_horizon_autocorrelation_analysis,
    run_length_analysis,
    variance_ratio_test,
)
from src.features.base import FeatureBase
from src.features.eda_utils import (
    compute_daily_returns,
    plot_acf_squared_returns,
    plot_correlation_matrix,
    plot_price_series,
    plot_returns_distribution,
    plot_rolling_volatility,
    plot_seasonality,
    plot_volatility_regimes,
    summary_stats_table,
)
from src.features.feature_registry import (
    FeatureMetadata,
    FeatureRegistry,
    feature_registry,
    register_feature,
)
from src.features.feature_scaling import (
    CrossSectionalScaler,
    FeaturePipeline,
    TimeSeriesScaler,
)
from src.features.feature_selection import (
    compute_multicollinearity,
    compute_tree_importance,
    compute_univariate_metrics,
    feature_selection_report,
    make_target,
)
from src.features.mean_reversion_features import (
    MeanReversionFeatureExtractor,
    compute_atr,
    compute_bollinger_bands,
    compute_ma_distance,
    compute_price_zscore,
    compute_rolling_half_life,
    compute_rsi_reversion,
    compute_stochastic_oscillator,
    compute_true_range,
    estimate_half_life,
)
from src.features.microstructure_proxies import (
    MicrostructureProxyFeatureExtractor,
    compute_corwin_schultz_spread,
    compute_garman_klass_volatility,
    compute_parkinson_volatility,
    compute_roll_spread,
    compute_vpin_proxy,
)
from src.features.momentum_features import (
    MomentumFeatureExtractor,
    compute_cross_sectional_momentum,
    compute_jegadeesh_titman_momentum,
    compute_ma_crossover,
    compute_macd,
    compute_price_momentum,
    compute_rate_of_change,
    compute_rsi,
)
from src.features.regime_detection import (
    RegimeFeatureExtractor,
    RegimeModelResult,
    fit_gmm_regimes,
    fit_hmm_regimes,
    rolling_regime_features,
)
from src.features.stationarity import (
    ADFResult,
    KPSSResult,
    StationarityReport,
    adf_test,
    difference_series,
    kpss_test,
    stationarity_report,
    test_multiple_series,
)
from src.features.volatility_analysis import (
    ARCHLMResult,
    LjungBoxResult,
    VolatilityClusteringReport,
    arch_lm_test,
    batch_volatility_clustering,
    compute_acf_series,
    compute_volatility_proxies,
    ljung_box_test,
    volatility_clustering_report,
)
from src.features.volatility_models import (
    GARCHModelResult,
    GARCHVolatilityFeatureExtractor,
    fit_egarch,
    fit_garch,
    fit_gjr_garch,
    forecast_volatility,
    rolling_garch_features,
    select_best_volatility_model,
)
from src.features.volume_features import (
    VolumeFeatureExtractor,
    compute_adl,
    compute_amihud_illiquidity,
    compute_cmf,
    compute_obv,
    compute_volume_roc,
    compute_volume_zscore,
    compute_vwap,
)

__all__ = [
    # Feature framework & registry
    "FeatureBase",
    "FeatureMetadata",
    "FeatureRegistry",
    "feature_registry",
    "register_feature",
    # Momentum features
    "compute_price_momentum",
    "compute_jegadeesh_titman_momentum",
    "compute_rate_of_change",
    "compute_ma_crossover",
    "compute_rsi",
    "compute_macd",
    "compute_cross_sectional_momentum",
    "MomentumFeatureExtractor",
    # Mean-reversion features
    "compute_price_zscore",
    "compute_bollinger_bands",
    "compute_rsi_reversion",
    "compute_true_range",
    "compute_atr",
    "compute_ma_distance",
    "estimate_half_life",
    "compute_rolling_half_life",
    "compute_stochastic_oscillator",
    "MeanReversionFeatureExtractor",
    # Volume features
    "compute_obv",
    "compute_vwap",
    "compute_adl",
    "compute_cmf",
    "compute_volume_roc",
    "compute_volume_zscore",
    "compute_amihud_illiquidity",
    "VolumeFeatureExtractor",
    # Microstructure proxies
    "compute_corwin_schultz_spread",
    "compute_roll_spread",
    "compute_vpin_proxy",
    "compute_garman_klass_volatility",
    "compute_parkinson_volatility",
    "MicrostructureProxyFeatureExtractor",
    # EDA utilities
    "compute_daily_returns",
    "summary_stats_table",
    "plot_price_series",
    "plot_returns_distribution",
    "plot_correlation_matrix",
    "plot_rolling_volatility",
    "plot_seasonality",
    "plot_acf_squared_returns",
    "plot_volatility_regimes",
    # Stationarity testing
    "ADFResult",
    "KPSSResult",
    "StationarityReport",
    "adf_test",
    "kpss_test",
    "stationarity_report",
    "test_multiple_series",
    "difference_series",
    # Volatility clustering analysis
    "ARCHLMResult",
    "LjungBoxResult",
    "VolatilityClusteringReport",
    "compute_volatility_proxies",
    "compute_acf_series",
    "ljung_box_test",
    "arch_lm_test",
    "volatility_clustering_report",
    "batch_volatility_clustering",
    # Volatility models (GARCH)
    "GARCHModelResult",
    "fit_garch",
    "fit_gjr_garch",
    "fit_egarch",
    "select_best_volatility_model",
    "forecast_volatility",
    "rolling_garch_features",
    "GARCHVolatilityFeatureExtractor",
    # Autocorrelation & momentum diagnostics
    "AutocorrelationReport",
    "LjungBoxRawResult",
    "RunLengthResult",
    "VarianceRatioResult",
    "compute_acf_pacf",
    "ljung_box_raw",
    "variance_ratio_test",
    "run_length_analysis",
    "autocorrelation_report",
    "multi_horizon_autocorrelation_analysis",
    "multi_asset_autocorrelation_summary",
    # Regime detection
    "RegimeModelResult",
    "fit_hmm_regimes",
    "fit_gmm_regimes",
    "rolling_regime_features",
    "RegimeFeatureExtractor",
    # Feature scaling & pipeline
    "TimeSeriesScaler",
    "CrossSectionalScaler",
    "FeaturePipeline",
    # Feature selection & target engineering
    "make_target",
    "compute_univariate_metrics",
    "compute_multicollinearity",
    "compute_tree_importance",
    "feature_selection_report",
]
