# ============================================================
# Portfolio Risk Engine & Safety Gate (Phase 39)
# ============================================================
"""
Production Risk Engine and Execution Safety Layer.

=============================================================================
CRITICAL ARCHITECTURAL DESIGN PRINCIPLE: THE SUPREMACY OF RISK
-----------------------------------------------------------------------------
The Risk Engine sits independent of and strictly ABOVE any model, strategy, or
order-generation pipeline.

1. Hard Architectural Rule (Non-Bypassable Gate):
   - Every single order intent generated by any strategy (directional ML, pairs
     trading, mean-reversion, or manual override) MUST pass through and be
     evaluated by the Risk Engine before reaching the execution layer / broker.
   - The Risk Engine has absolute authority to BLOCK or RESIZE any order.
   - Strategy and ML signals NEVER override Risk Engine decisions. If a model
     predicts a 99% win probability with 5x leverage, but the portfolio is in a
     drawdown halt, the order is categorically BLOCKED.

2. Defense-in-Depth Safety Rules:
   - Maximum Drawdown Kill Switch:
     Halt all new position openings if running portfolio drawdown exceeds the
     limit (e.g. 15-20%). Only de-risking and position-closing trades are approved.
   - Daily Loss Limit (Prop-Desk Circuit Breaker):
     Halt trading for the remainder of the session if intra-day losses
     (realized + unrealized) breach a hard threshold (e.g. 3-5%).
   - Position and Exposure Limits:
     Enforce single-asset caps (respecting Phase 35 Kelly caps), aggregate
     gross leverage caps, net market exposure ceilings, and sector concentration.
   - Dynamic Volatility-Based De-risking:
     Directly connected to Phase 14 GARCH volatility forecasting. When conditional
     volatility spikes above historical norms, position sizes are automatically
     and proportionally hair-cutted.

3. Full Auditability:
   - Every intervention (blocked orders, size reductions, triggered circuit
     breakers) is recorded with complete context (timestamp, ticker, rule triggered,
     original size vs approved size, rationale) for audit trails (Phase 47).
=============================================================================
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from enum import Enum
from typing import Any, Callable, Sequence

import pandas as pd

from src.utils.logger import get_logger

logger = get_logger(__name__)


# ============================================================
# 1. Enums and Data Containers
# ============================================================


class OrderAction(str, Enum):
    """Trading action direction."""

    BUY = "BUY"
    SELL = "SELL"


class DecisionStatus(str, Enum):
    """Risk engine evaluation outcome."""

    APPROVED = "APPROVED"
    RESIZED = "RESIZED"
    BLOCKED = "BLOCKED"


class RiskRule(str, Enum):
    """Specific safety rule triggering intervention."""

    NONE = "NONE"
    DRAWDOWN_KILL_SWITCH = "DRAWDOWN_KILL_SWITCH"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    POSITION_LIMIT = "POSITION_LIMIT"
    GROSS_EXPOSURE_LIMIT = "GROSS_EXPOSURE_LIMIT"
    NET_EXPOSURE_LIMIT = "NET_EXPOSURE_LIMIT"
    SECTOR_CONCENTRATION_LIMIT = "SECTOR_CONCENTRATION_LIMIT"
    VOLATILITY_DERISKING = "VOLATILITY_DERISKING"


@dataclass
class RiskConfig:
    """Configuration parameters for portfolio risk rules."""

    max_drawdown_pct: float = 0.15  # 15% drawdown halts new risk
    daily_loss_limit_pct: float = 0.03  # 3% daily loss circuit breaker
    max_position_size_pct: float = 0.25  # 25% single-asset Kelly cap
    max_gross_exposure: float = 1.0  # 100% maximum gross leverage
    max_net_exposure: float = 1.0  # 100% maximum net market exposure
    max_sector_concentration: float = 0.40  # 40% maximum per sector
    vol_spike_threshold: float = 1.50  # GARCH vol > 1.5x baseline triggers de-risking
    min_vol_derisk_multiplier: float = 0.20  # Minimum position scale floor under extreme vol
    sector_mappings: dict[str, str] = field(
        default_factory=lambda: {
            "AAPL": "Technology",
            "MSFT": "Technology",
            "NVDA": "Technology",
            "GOOGL": "Communication",
            "AMZN": "ConsumerDiscretionary",
            "TSLA": "ConsumerDiscretionary",
            "SPY": "BroadMarket",
            "QQQ": "BroadTech",
            "XLK": "Technology",
        }
    )


@dataclass
class PortfolioState:
    """Current dynamic state of the investment portfolio."""

    current_equity: float
    peak_equity: float
    daily_start_equity: float
    current_date: str | date | datetime
    positions: dict[str, float] = field(default_factory=dict)  # ticker -> current market value
    realized_pnl_today: float = 0.0
    unrealized_pnl_today: float = 0.0

    @property
    def current_drawdown(self) -> float:
        """Current drawdown from peak equity as a positive fraction."""
        if self.peak_equity <= 0.0:
            return 0.0
        dd = (self.peak_equity - self.current_equity) / self.peak_equity
        return max(0.0, float(dd))

    @property
    def daily_loss_pct(self) -> float:
        """Total intra-day loss as a positive fraction of daily start equity."""
        if self.daily_start_equity <= 0.0:
            return 0.0
        total_pnl = self.realized_pnl_today + self.unrealized_pnl_today
        if total_pnl >= 0:
            return 0.0
        return float(abs(total_pnl) / self.daily_start_equity)

    @property
    def gross_exposure_value(self) -> float:
        """Total dollar value of all open long and short positions."""
        return float(sum(abs(val) for val in self.positions.values()))

    @property
    def gross_exposure_pct(self) -> float:
        """Gross exposure as a fraction of current equity."""
        if self.current_equity <= 0.0:
            return 0.0
        return float(self.gross_exposure_value / self.current_equity)

    @property
    def net_exposure_value(self) -> float:
        """Net dollar exposure (longs minus shorts)."""
        return float(sum(self.positions.values()))

    @property
    def net_exposure_pct(self) -> float:
        """Net exposure as a fraction of current equity."""
        if self.current_equity <= 0.0:
            return 0.0
        return float(abs(self.net_exposure_value) / self.current_equity)


@dataclass
class OrderIntent:
    """Order intent generated by a model or strategy requiring risk clearance."""

    ticker: str
    action: OrderAction | str
    quantity: float
    price: float
    order_type: str = "MARKET"
    timestamp: str | datetime | None = None
    is_closing: bool = False  # If True, order closes or reduces existing exposure
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def dollar_value(self) -> float:
        """Estimated total dollar value of the order."""
        return float(abs(self.quantity * self.price))


@dataclass
class OrderDecision:
    """Final decision rendered by the risk engine for an order intent."""

    status: DecisionStatus
    intent: OrderIntent
    approved_quantity: float
    approved_dollar_value: float
    rule_triggered: RiskRule = RiskRule.NONE
    reasons: list[str] = field(default_factory=list)
    timestamp: str | datetime | None = None

    def to_audit_dict(self) -> dict[str, Any]:
        """Convert decision to structured dictionary for audit logging."""
        return {
            "timestamp": str(self.timestamp) if self.timestamp else str(datetime.now()),
            "ticker": self.intent.ticker,
            "action": _normalize_action(self.intent.action),
            "status": str(self.status.value),
            "rule_triggered": str(self.rule_triggered.value),
            "requested_quantity": round(float(self.intent.quantity), 4),
            "approved_quantity": round(float(self.approved_quantity), 4),
            "requested_value": round(float(self.intent.dollar_value), 2),
            "approved_value": round(float(self.approved_dollar_value), 2),
            "reasons": "; ".join(self.reasons) if self.reasons else "Within risk parameters",
        }


# ============================================================
# 2. Risk Engine Core Implementation
# ============================================================


def _normalize_action(action: OrderAction | str) -> str:
    """Normalize action to uppercase 'BUY' or 'SELL'."""
    if isinstance(action, OrderAction):
        return action.value.upper()
    s = str(action).upper()
    if "." in s:
        s = s.split(".")[-1]
    return s


class RiskEngine:
    """Central risk gatekeeper and execution authority.

    This engine inspects every order against four defense-in-depth safety layers:
    1. Maximum Drawdown Kill Switch
    2. Daily Loss Limit Circuit Breaker
    3. Position and Exposure Caps (Single-Asset, Gross, Net, Sector)
    4. Volatility-Based De-risking (GARCH Forecasts)
    """

    def __init__(self, config: RiskConfig | None = None) -> None:
        """Initialize the risk engine with configurable limits."""
        self.config = config or RiskConfig()
        self.audit_log: list[OrderDecision] = []
        self._kill_switch_active: bool = False
        self._circuit_breaker_active: bool = False
        self._circuit_breaker_date: Any = None

    def reset_daily_circuit_breaker(self, new_date: Any) -> None:
        """Reset the intra-day circuit breaker if entering a new trading day."""
        if self._circuit_breaker_date != new_date:
            self._circuit_breaker_active = False
            self._circuit_breaker_date = new_date
            logger.info("Daily circuit breaker reset for date %s", new_date)

    def is_order_reducing_exposure(
        self,
        intent: OrderIntent,
        portfolio: PortfolioState,
    ) -> bool:
        """Determine if an order reduces or closes an existing position."""
        if intent.is_closing:
            return True

        curr_pos = portfolio.positions.get(intent.ticker, 0.0)
        if curr_pos == 0.0:
            return False

        action_norm = _normalize_action(intent.action)
        # Long position: SELL reduces exposure
        if curr_pos > 0 and action_norm == "SELL":
            return True
        # Short position: BUY reduces exposure
        if curr_pos < 0 and action_norm == "BUY":
            return True

        return False

    def compute_volatility_derisk_multiplier(
        self,
        forecast_vol: float,
        baseline_vol: float,
    ) -> float:
        """Calculate dynamic sizing multiplier based on GARCH volatility spikes.

        Multiplier kappa = min(1.0, baseline_vol / forecast_vol).
        """
        if baseline_vol <= 0.0 or forecast_vol <= 0.0:
            return 1.0

        vol_ratio = forecast_vol / baseline_vol
        if vol_ratio <= self.config.vol_spike_threshold:
            return 1.0

        # Scale down inversely with volatility excess
        multiplier = baseline_vol / forecast_vol
        clamped = max(self.config.min_vol_derisk_multiplier, min(1.0, float(multiplier)))
        return round(clamped, 4)

    def evaluate_order(
        self,
        intent: OrderIntent,
        portfolio: PortfolioState,
        market_volatility: dict[str, tuple[float, float]] | None = None,
    ) -> OrderDecision:
        """Evaluate a single order intent against all safety gates.

        Parameters
        ----------
        intent : OrderIntent
            Proposed trade intent.
        portfolio : PortfolioState
            Current portfolio state.
        market_volatility : dict[str, tuple[float, float]], optional
            Mapping ticker -> (forecast_vol, baseline_vol) from Phase 14 GARCH.

        Returns
        -------
        OrderDecision
            Decision containing approved sizing and audit rationale.
        """
        # Auto-update calendar day for circuit breaker
        self.reset_daily_circuit_breaker(portfolio.current_date)

        is_reduction = self.is_order_reducing_exposure(intent, portfolio)
        reasons: list[str] = []
        rule_triggered = RiskRule.NONE

        # ------------------------------------------------------------
        # Layer 1: Maximum Drawdown Kill Switch
        # ------------------------------------------------------------
        current_dd = portfolio.current_drawdown
        if current_dd >= self.config.max_drawdown_pct:
            self._kill_switch_active = True
            if not is_reduction:
                msg = (
                    f"Max drawdown breached ({current_dd:.2%} >= {self.config.max_drawdown_pct:.2%}). "
                    "Kill switch ACTIVE: New position openings blocked."
                )
                logger.warning(msg)
                decision = OrderDecision(
                    status=DecisionStatus.BLOCKED,
                    intent=intent,
                    approved_quantity=0.0,
                    approved_dollar_value=0.0,
                    rule_triggered=RiskRule.DRAWDOWN_KILL_SWITCH,
                    reasons=[msg],
                    timestamp=intent.timestamp,
                )
                self.audit_log.append(decision)
                return decision
            else:
                reasons.append("Drawdown kill switch active: Position-reducing order permitted.")
        else:
            self._kill_switch_active = False

        # ------------------------------------------------------------
        # Layer 2: Daily Loss Limit Circuit Breaker
        # ------------------------------------------------------------
        daily_loss = portfolio.daily_loss_pct
        if daily_loss >= self.config.daily_loss_limit_pct:
            self._circuit_breaker_active = True
            if not is_reduction:
                msg = (
                    f"Daily loss limit breached ({daily_loss:.2%} >= {self.config.daily_loss_limit_pct:.2%}). "
                    "Circuit breaker ACTIVE: Trading halted for remainder of the day."
                )
                logger.warning(msg)
                decision = OrderDecision(
                    status=DecisionStatus.BLOCKED,
                    intent=intent,
                    approved_quantity=0.0,
                    approved_dollar_value=0.0,
                    rule_triggered=RiskRule.DAILY_LOSS_LIMIT,
                    reasons=[msg],
                    timestamp=intent.timestamp,
                )
                self.audit_log.append(decision)
                return decision
            else:
                reasons.append("Daily loss circuit breaker active: De-risking order permitted.")

        # If order is purely closing/reducing existing exposure, allow full execution
        if is_reduction:
            decision = OrderDecision(
                status=DecisionStatus.APPROVED,
                intent=intent,
                approved_quantity=intent.quantity,
                approved_dollar_value=intent.dollar_value,
                rule_triggered=rule_triggered,
                reasons=reasons or ["Risk-reducing order approved."],
                timestamp=intent.timestamp,
            )
            self.audit_log.append(decision)
            return decision

        # ------------------------------------------------------------
        # Layer 3: Volatility-Based De-risking (GARCH Link)
        # ------------------------------------------------------------
        approved_qty = float(intent.quantity)
        if market_volatility and intent.ticker in market_volatility:
            f_vol, b_vol = market_volatility[intent.ticker]
            multiplier = self.compute_volatility_derisk_multiplier(f_vol, b_vol)
            if multiplier < 1.0:
                approved_qty *= multiplier
                rule_triggered = RiskRule.VOLATILITY_DERISKING
                msg = (
                    f"Volatility spike detected (Forecast={f_vol:.2%}, Baseline={b_vol:.2%}). "
                    f"Position downscaled by factor {multiplier:.2f}."
                )
                reasons.append(msg)
                logger.info(msg)

        # ------------------------------------------------------------
        # Layer 4: Position and Exposure Caps
        # ------------------------------------------------------------
        equity = max(1.0, portfolio.current_equity)
        unit_price = max(1e-6, intent.price)

        # 4a. Single-Asset Position Cap (Kelly Cap)
        curr_asset_val = abs(portfolio.positions.get(intent.ticker, 0.0))
        max_asset_val = equity * self.config.max_position_size_pct
        proposed_asset_val = curr_asset_val + (approved_qty * unit_price)

        if proposed_asset_val > max_asset_val:
            allowed_add_val = max(0.0, max_asset_val - curr_asset_val)
            allowed_qty = allowed_add_val / unit_price
            if allowed_qty <= 0.0:
                msg = (
                    f"Single asset limit reached for {intent.ticker} "
                    f"({curr_asset_val/equity:.1%} >= {self.config.max_position_size_pct:.1%})."
                )
                decision = OrderDecision(
                    status=DecisionStatus.BLOCKED,
                    intent=intent,
                    approved_quantity=0.0,
                    approved_dollar_value=0.0,
                    rule_triggered=RiskRule.POSITION_LIMIT,
                    reasons=[msg],
                    timestamp=intent.timestamp,
                )
                self.audit_log.append(decision)
                return decision

            rule_triggered = RiskRule.POSITION_LIMIT
            reasons.append(
                f"Single-asset cap applied: Resized from {approved_qty:.2f} to {allowed_qty:.2f} shares."
            )
            approved_qty = allowed_qty

        # 4b. Sector Concentration Cap
        sector = self.config.sector_mappings.get(intent.ticker, "Unknown")
        if sector != "Unknown":
            curr_sector_val = sum(
                abs(val)
                for t, val in portfolio.positions.items()
                if self.config.sector_mappings.get(t) == sector
            )
            max_sector_val = equity * self.config.max_sector_concentration
            proposed_sector_val = curr_sector_val + (approved_qty * unit_price)

            if proposed_sector_val > max_sector_val:
                allowed_sector_add = max(0.0, max_sector_val - curr_sector_val)
                allowed_qty_sec = allowed_sector_add / unit_price
                if allowed_qty_sec <= 0.0:
                    msg = (
                        f"Sector limit reached for {sector} "
                        f"({curr_sector_val/equity:.1%} >= {self.config.max_sector_concentration:.1%})."
                    )
                    decision = OrderDecision(
                        status=DecisionStatus.BLOCKED,
                        intent=intent,
                        approved_quantity=0.0,
                        approved_dollar_value=0.0,
                        rule_triggered=RiskRule.SECTOR_CONCENTRATION_LIMIT,
                        reasons=[msg],
                        timestamp=intent.timestamp,
                    )
                    self.audit_log.append(decision)
                    return decision

                rule_triggered = RiskRule.SECTOR_CONCENTRATION_LIMIT
                reasons.append(
                    f"Sector concentration cap for {sector}: Resized to {allowed_qty_sec:.2f} shares."
                )
                approved_qty = min(approved_qty, allowed_qty_sec)

        # 4c. Gross Exposure Cap
        curr_gross = portfolio.gross_exposure_value
        max_gross = equity * self.config.max_gross_exposure
        proposed_gross = curr_gross + (approved_qty * unit_price)

        if proposed_gross > max_gross:
            allowed_gross_add = max(0.0, max_gross - curr_gross)
            allowed_qty_gross = allowed_gross_add / unit_price
            if allowed_qty_gross <= 0.0:
                msg = f"Gross portfolio exposure ceiling reached ({portfolio.gross_exposure_pct:.1%})."
                decision = OrderDecision(
                    status=DecisionStatus.BLOCKED,
                    intent=intent,
                    approved_quantity=0.0,
                    approved_dollar_value=0.0,
                    rule_triggered=RiskRule.GROSS_EXPOSURE_LIMIT,
                    reasons=[msg],
                    timestamp=intent.timestamp,
                )
                self.audit_log.append(decision)
                return decision

            rule_triggered = RiskRule.GROSS_EXPOSURE_LIMIT
            reasons.append(f"Gross exposure limit: Resized to {allowed_qty_gross:.2f} shares.")
            approved_qty = min(approved_qty, allowed_qty_gross)

        # 4d. Net Exposure Cap
        order_dir = 1.0 if _normalize_action(intent.action) == "BUY" else -1.0
        curr_net = portfolio.net_exposure_value
        max_net = equity * self.config.max_net_exposure
        proposed_net = abs(curr_net + (order_dir * approved_qty * unit_price))

        if proposed_net > max_net:
            msg = f"Net portfolio exposure limit reached ({proposed_net/equity:.1%})."
            decision = OrderDecision(
                status=DecisionStatus.BLOCKED,
                intent=intent,
                approved_quantity=0.0,
                approved_dollar_value=0.0,
                rule_triggered=RiskRule.NET_EXPOSURE_LIMIT,
                reasons=[msg],
                timestamp=intent.timestamp,
            )
            self.audit_log.append(decision)
            return decision

        # Determine Final Status
        approved_val = approved_qty * unit_price
        if approved_qty < intent.quantity:
            status = DecisionStatus.RESIZED
        else:
            status = DecisionStatus.APPROVED
            if not reasons:
                reasons.append("All risk criteria satisfied.")

        decision = OrderDecision(
            status=status,
            intent=intent,
            approved_quantity=float(approved_qty),
            approved_dollar_value=float(approved_val),
            rule_triggered=rule_triggered,
            reasons=reasons,
            timestamp=intent.timestamp,
        )
        self.audit_log.append(decision)
        return decision

    def filter_orders(
        self,
        intents: Sequence[OrderIntent],
        portfolio: PortfolioState,
        market_volatility: dict[str, tuple[float, float]] | None = None,
    ) -> list[OrderDecision]:
        """Evaluate a batch of order intents sequentially, updating portfolio state in flight."""
        decisions: list[OrderDecision] = []
        running_portfolio = PortfolioState(
            current_equity=portfolio.current_equity,
            peak_equity=portfolio.peak_equity,
            daily_start_equity=portfolio.daily_start_equity,
            current_date=portfolio.current_date,
            positions=dict(portfolio.positions),
            realized_pnl_today=portfolio.realized_pnl_today,
            unrealized_pnl_today=portfolio.unrealized_pnl_today,
        )

        for intent in intents:
            decision = self.evaluate_order(intent, running_portfolio, market_volatility)
            decisions.append(decision)

            # Update running portfolio positions if approved or resized
            if (
                decision.status in (DecisionStatus.APPROVED, DecisionStatus.RESIZED)
                and decision.approved_quantity > 0
            ):
                direction = 1.0 if _normalize_action(intent.action) == "BUY" else -1.0
                curr_pos = running_portfolio.positions.get(intent.ticker, 0.0)
                running_portfolio.positions[intent.ticker] = curr_pos + (
                    direction * decision.approved_dollar_value
                )

        return decisions

    def execute_gated_order(
        self,
        intent: OrderIntent,
        portfolio: PortfolioState,
        broker_execute_fn: Callable[[OrderIntent, float], Any],
        market_volatility: dict[str, tuple[float, float]] | None = None,
    ) -> tuple[OrderDecision, Any]:
        """Enforce the non-bypassable architectural gate.

        Executes the order with the broker ONLY if approved or resized.
        Raises PermissionError if a blocked order is attempted to be executed.
        """
        decision = self.evaluate_order(intent, portfolio, market_volatility)

        if decision.status == DecisionStatus.BLOCKED or decision.approved_quantity <= 0:
            logger.error("Order execution halted by RiskEngine: %s", decision.reasons)
            raise PermissionError(
                f"Order for {intent.ticker} was BLOCKED by RiskEngine: {'; '.join(decision.reasons)}"
            )

        broker_result = broker_execute_fn(intent, decision.approved_quantity)
        return decision, broker_result

    def get_audit_log(self) -> pd.DataFrame:
        """Return the complete audit trail of risk decisions as a DataFrame."""
        if not self.audit_log:
            return pd.DataFrame(
                columns=[
                    "timestamp",
                    "ticker",
                    "action",
                    "status",
                    "rule_triggered",
                    "requested_quantity",
                    "approved_quantity",
                    "requested_value",
                    "approved_value",
                    "reasons",
                ]
            )
        return pd.DataFrame([d.to_audit_dict() for d in self.audit_log])
